### ISSUE TITLE
Images are not displayed in the preview

### ISSUE THREAD

**Issue by speendo** [bittner/gedit-reST-plugin#7]
When referencing an image in gedit 3.14, there is just an empty box in the preview - the image is not displayed.

See an example on the screenshot
http://i58.tinypic.com/25qu4js.png

**Comment by bittner** [comment]
We're making some progress here: The problem is related to the underlying WebKit rendering engine for Gtk. The plugin must make sure that WebKit sees relative links coming from local, i.e. using the `file://` protocol in the URI, otherwise it will refuse to display that content for security reasons.

More specific information for anyone interested is found on the [webkit-gtk mailing list](https://lists.webkit.org/pipermail/webkit-gtk/2015-January/002211.html).

**Comment by speendo** [comment]
I see :)

**Comment by bittner** [comment]
Images are now loaded. You can test the plugin from the `gedit-3.14` branch.

**Comment by speendo** [comment]
Yes, I can confirm that!

Thank you!
